# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Trevor Knox
title: Computer Sceince Reasearcher and Student
email: tkk5189@psu.edu
website: www.trevorknox.com

# Social links
twitter_username: 
github_username:  tkk5189
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: knoxtrevor
linkedin_username: Trevor Knox
# pinterest_username: jekyll
youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Trevor and I'm a computer science student and researcher. As well as pursuing a degree in computer science, I am also a member of Penn State's MC REU, and work as a student researcher for the NSF.

  I am most skilled in: <mark>Python</mark> and <mark>C#</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in artificial intelligence and virtual reality some of my other interests and hobbies are:
   - Playing Guitar
   - Gaming
   - Weightlifting

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
